# Generated by Django 5.2.4 on 2025-07-22 11:34

import devis_app.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='prix_unitaire',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='client',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='client',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='date_expiration',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='lignedevis',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.AddField(
            model_name='devis',
            name='date_emission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='devis',
            name='date_proforma',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='devis',
            name='date_validite',
            field=models.DateField(default=devis_app.models.default_date_validite),
        ),
        migrations.AddField(
            model_name='devis',
            name='detail_proposition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='devis',
            name='numero_devis',
            field=models.CharField(default=devis_app.models.generate_numero_devis, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='devis',
            name='regime_vente',
            field=models.CharField(default='TTC', max_length=10),
        ),
        migrations.AddField(
            model_name='devis',
            name='total_ht',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='devis',
            name='total_ht_remise',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='devis',
            name='total_remise',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='devis',
            name='total_ttc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='devis',
            name='total_ttc_lettres',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='devis',
            name='tva',
            field=models.FloatField(default=18.0),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='detail_proposition',
            field=models.TextField(default='Sans nom'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='pu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='remise',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='unite',
            field=models.CharField(default='unité', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis_app.devis'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devis_app.categorie'),
        ),
    ]
