# Generated by Django 5.2.4 on 2025-07-22 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0002_categorie_rename_prix_unitaire_produit_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devis_app.produit'),
        ),
    ]
