# Generated by Django 5.2.4 on 2025-07-22 12:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0003_lignedevis_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devis',
            name='total_ht_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devis',
            name='total_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devis',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devis',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.0'), max_digits=5),
        ),
    ]
