# Generated by Django 5.2.4 on 2025-07-22 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0004_alter_devis_total_ht_alter_devis_total_ht_remise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedevis',
            name='detail_proposition',
        ),
        migrations.AddField(
            model_name='devis',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devis_app.client'),
        ),
    ]
