# Generated by Django 5.2.4 on 2025-08-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0006_client_adresse_client_date_creation_client_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='devis_app.client'),
        ),
    ]
