# Generated by Django 5.2.4 on 2025-09-05 19:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0007_alter_devis_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='numero_devis',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
