# Generated by Django 5.2.4 on 2025-09-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0008_devis_slug_alter_devis_numero_devis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
