# Generated by Django 5.2.4 on 2025-09-13 22:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0009_client_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
