# Generated by Django 5.2.4 on 2025-09-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0010_devis_total_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='regime_vente',
            field=models.CharField(default='TTC(CFA)', max_length=10),
        ),
    ]
