# Generated by Django 5.2.4 on 2025-09-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0011_alter_devis_regime_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='appliquer_tva',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='regime_vente',
            field=models.CharField(default='TTC (CFA)', max_length=50),
        ),
    ]
