# Generated by Django 5.2.4 on 2025-10-08 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0012_devis_appliquer_tva_alter_devis_regime_vente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis_utilisateur', to=settings.AUTH_USER_MODEL),
        ),
    ]
