# Generated by Django 5.2.4 on 2025-10-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0016_pointvente_remove_devis_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='regime_vente',
            field=models.CharField(choices=[('TTC (CFA)', 'TTC (CFA)'), ('HT (CFA)', 'HT (CFA)'), ('EURO TTC', 'EURO TTC'), ('EURO HT', 'EURO HT')], default='TTC (CFA)', max_length=50),
        ),
    ]
