# Generated by Django 5.2.4 on 2025-10-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0017_alter_devis_regime_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='regime_vente',
            field=models.CharField(choices=[('TTC (CFA)', 'TTC (CFA)')], default='TTC (CFA)', max_length=50),
        ),
    ]
