# Generated by Django 5.2.4 on 2025-11-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0018_alter_devis_regime_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
