# Generated by Django 5.2.4 on 2025-11-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0019_profile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvente',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro du point de vente'),
        ),
    ]
