# Generated by Django 5.2.4 on 2026-01-28 11:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0020_pointvente_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='pourcentage_acompte',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5, verbose_name="Pourcentage d'acompte"),
        ),
        migrations.AddField(
            model_name='devis',
            name='pourcentage_livraison',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5, verbose_name='Pourcentage à la livraison'),
        ),
    ]
