# Generated by Django 5.2.4 on 2026-01-28 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0021_devis_pourcentage_acompte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification')], max_length=50)),
                ('donnees_avant', models.JSONField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='devis_app.devis')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de devis',
                'verbose_name_plural': 'Historiques des devis',
                'ordering': ['-date_modification'],
            },
        ),
    ]
