# Generated by Django 5.2.4 on 2026-02-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0022_historiquedevis'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='nom_responsable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du responsable commercial'),
        ),
        migrations.AddField(
            model_name='devis',
            name='signature_electronique',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature électronique'),
        ),
    ]
