# Generated by Django 5.2.4 on 2026-03-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0023_devis_nom_responsable_devis_signature_electronique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsableCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom complet')),
            ],
            options={
                'verbose_name': 'Responsable Commercial',
                'verbose_name_plural': 'Responsables Commerciaux',
                'ordering': ['nom'],
            },
        ),
    ]
